services:
  - type: web
    name: MammaMia  
    runtime: python  
    buildCommand: pip install -r requirements.txt  
    startCommand: python3 run.py  
    plan: free 
    region: frankfurt
    envVars:
      - key: PORT
        value: 8080
      - key: TMDB_KEY
        sync: false
      - key: PROXY
        sync: false
      - key: PROXY_CREDENTIALS
        value: '[{"proxy": "http://lmtokumm-rotate:5xehmu0hve87@p.webshare.io:80/"}]'
