services:
  - type: web
    name: MammaMia  
    runtime: python  
    buildCommand: pip install -r requirements.txt  
    startCommand: python3 run.py  
    plan: free 
    region: frankfurt
    envVars:
      - key: PORT
        value: 8080
      - key: TMDB_KEY
        sync: false
      - key: PROXY_CREDENTIALS
        sync: false
